Replaced `std::this_thread::sleep_for` with just `Sleep` in `windows_api_test` because in MinGW `std::this_thread::sleep_for` seems to be broken because it uses `nanosleep`, which can be unavailable in MinGW, causing `undefined reference to `nanosleep'`.